### PR TITLE
Added Dutch translation

### PR DESCRIPTION
**Pull request by Vistaus**
🙂

### CODE REVIEW

**Comment by lukmarcus** [comment]
So this project is coming back to life?

**Comment by Vistaus** [comment]
> So this project is coming back to life?

There were commits two weeks ago, so I'd say yes.

**Comment by lukmarcus** [comment]
@agateau It's coming back to life?

**Comment by agateau** [comment]
@Vistaus Thanks for this work, looking at it right now.

@lukmarcus It's not related to this translation, but I am updating the game to make it build with more recent versions of the Android SDK and libgdx, so that it stays available on Google Play.

I do not plan to make any real changes: the game is done as far as I am concerned, so not sure the work I am doing can be considered as making the project "coming back to life". Once this refresh is done, I want to look into #1 and #2 though.

**Review by agateau — CHANGES_REQUESTED** [review]
I merged my latest changes in your branch and fixed a few minor issues. It looks good so far except for one sentence which is too long:

image

Is there a way to shorten it? If not I can look into making the code wrap it on 2 lines, but that may take some time.

**Comment by Vistaus** [comment]
You're right, I'll look into it right away.

**Comment by Vistaus** [comment]
I've shortened it - thanks for the heads-up!

**Review by agateau — APPROVED** [review]

**Comment by Vistaus** [comment]
Thanks for notifying me about the updated strings! I just opened a new PR with the newly translated strings. 🙂

**Pull request closed without merging**
